apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: production-pod-delete
  namespace: compliance
spec:
  appinfo:
    appns: compliance
    applabel: app=intake-gateway
    appkind: deployment
  chaosServiceAccount: litmus-admin
  annotationCheck: 'true'
  engineState: 'active'
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "15"
            - name: FORCE
              value: "true"
            - name: LIVENESS_CHECK
              value: "true"
            - name: AUTO_ABORT_CONDITIONS
              value: >
                {
                  "errorRate": "gt:5",
                  "latencyP99": "gt:2000"
                }
