from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from weasyprint import HTML
import datetime

app = FastAPI(title="PDF Generator", version="1.0")

class ReportRequest(BaseModel):
    document_id: str
    status: str
    fraud_probability: float = 0.0
    compliance_result: str = "passed"
    shap_explanation: list = []

@app.post("/generate")
async def generate_pdf(req: ReportRequest):
    template = f"""
    <html>
    <head><meta charset="utf-8"><title>Compliance Report</title></head>
    <body>
        <h1>Compliance Report</h1>
        <p>Document ID: {req.document_id}</p>
        <p>Date: {datetime.datetime.now().isoformat()}</p>
        <h2>Results</h2>
        <table border="1" cellpadding="5">
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Status</td><td>{req.status}</td></tr>
            <tr><td>Fraud Probability</td><td>{req.fraud_probability}</td></tr>
            <tr><td>Compliance</td><td>{req.compliance_result}</td></tr>
        </table>
        <p>Generated by Lexicon Compliance Platform</p>
    </body>
    </html>
    """
    try:
        pdf = HTML(string=template).write_pdf()
        return Response(content=pdf, media_type="application/pdf",
                       headers={"Content-Disposition": f"attachment; filename=report-{req.document_id}.pdf"})
    except Exception as e:
        raise HTTPException(500, f"PDF generation failed: {str(e)}")

@app.get("/health")
async def health():
    return {"status": "ok"}
